services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --requirepass ${REDISPASSWORD:?Must provide a REDISPASSWORD in environment}

    volumes:
      - redis:/data
volumes:
  redis: